"""
Integration tests for text continuation checking.

Coverage:
  - Likely mid-sentence continuations: 500 hand-written coherent sentences,
    each split at 30/40/50/60/70 ratios = 2,500 cases.
  - Likely mid-word / hyphenation continuations: ~80 bespoke cases.
  - Unlikely continuations: first half of sentence i paired with the
    second half of sentence (i + OFFSET) % 500 = 500 unrelated pairs.

Each test hits POST /v1/text/check-continuation on the live service.
"""

import pytest
from helpers import continuation_check


# ═══════════════════════════════════════════════════════════════════════
#  500-sentence pool — each ≥10 words, topically diverse
# ═══════════════════════════════════════════════════════════════════════

SENTENCE_POOL = [
    # Nature, weather, wildlife (0-49)
    "Heavy rainfall caused severe flooding throughout the coastal region last week and displaced hundreds of families.",
    "Fresh snowfall blanketed the mountain peaks and created a spectacular winter view for the hiking community.",
    "Thunder rumbled in the distance as dark clouds gathered ominously above the quiet valley below.",
    "The autumn leaves fell gently from the ancient oak trees lining the village main street.",
    "A thick fog rolled in from the coast and obscured the road for several miles inland.",
    "Wildflowers bloomed across the meadow after the first warm rain of the early spring season.",
    "The mountain stream carved a narrow path through the granite cliffs over thousands of years.",
    "Migrating geese flew in a perfect formation across the pale dawn sky this cold morning.",
    "The red fox darted across the frozen pond and disappeared into the thick underbrush quickly.",
    "Lightning struck a tall pine tree during the severe thunderstorm that swept through the region.",
    "The beaver family built an elaborate dam across the narrow creek behind the old farmhouse.",
    "Morning dew glistened on the spider webs stretched between the tall grass in the field.",
    "The hurricane made landfall near the coastal town shortly before the evening high tide arrived.",
    "Tulips bloomed in a riot of color throughout the park after the long winter finally ended.",
    "The eagle soared effortlessly on the warm updraft rising from the sun-heated desert floor below.",
    "Salmon fought their way upstream to spawn in the same gravel beds where they were hatched.",
    "The forest fire burned for three weeks before firefighters finally gained control of the eastern flank.",
    "Coral reefs teem with remarkable biodiversity that rivals the richness of any tropical rainforest on earth.",
    "The glacier has retreated nearly half a mile over the past thirty years of warming temperatures.",
    "Squirrels gathered acorns frantically before the first heavy frost of the season was forecasted to arrive.",
    "The desert bloomed with rare wildflowers after an unusually wet winter drenched the normally arid valley.",
    "A pod of dolphins swam alongside the fishing boat for nearly an hour off the rocky coast.",
    "The old willow tree finally toppled during the fierce windstorm that knocked out power lines everywhere.",
    "Hummingbirds visited the feeder dozens of times each hour throughout the long warm summer afternoons.",
    "The caves beneath the limestone plateau contain delicate formations that took millions of years to develop.",
    "Bears emerged from their winter dens much earlier than usual due to the remarkably mild temperatures.",
    "The meadow was alive with the sound of crickets and frogs calling on that warm summer evening.",
    "Acid rain has damaged the stone facades of cathedrals and monuments across much of central Europe.",
    "The tide pool revealed a small world of starfish anemones and hermit crabs to the curious children.",
    "Wolves reintroduced to the park have helped restore the ecological balance across the entire region.",
    "The comet was visible to the naked eye for several weeks during its closest approach to earth.",
    "Fireflies danced above the still waters of the small pond on that magical midsummer evening.",
    "The geyser erupted on schedule every ninety minutes delighting the large crowd of eager park visitors.",
    "Monarch butterflies completed their annual migration of thousands of miles to reach their winter refuge.",
    "The avalanche buried the remote cabin under fifteen feet of packed snow during the long night.",
    "Frogs emerged from their hibernation burrows and began calling for mates along the pond margin.",
    "The ancient redwood grove contains trees that were already centuries old when Rome was founded.",
    "Violent hailstorms pummeled the wheat fields and destroyed much of the season harvest within minutes.",
    "The harbor seal pup waited patiently on the rocks for its mother to return from fishing.",
    "Polar bears roamed the shrinking sea ice searching desperately for seals to sustain their hungry cubs.",
    "The volcanic eruption sent massive ash plumes thousands of feet into the atmosphere for several weeks.",
    "Cherry blossoms attracted thousands of visitors to the city park during the brief flowering season.",
    "Prairie dogs emerged from their burrows to bask in the afternoon sun across the vast grassland.",
    "The rainbow arched perfectly over the waterfall creating one of the most memorable sights of the trip.",
    "Sea turtles returned to the same beach where they had hatched decades earlier to lay their eggs.",
    "The night sky over the desert revealed thousands of stars normally hidden by urban light pollution.",
    "Mushrooms sprouted overnight across the forest floor after three days of steady autumn rainfall arrived.",
    "The lynx tracked its prey silently through the deep powder snow across the remote mountain ridge.",
    "Thermal vents on the ocean floor support unique ecosystems that thrive entirely without any sunlight whatsoever.",
    "The hawk circled high above the meadow scanning the ground carefully for any sign of movement.",
    # Science, research, technology (50-99)
    "Scientists discovered a new species of butterfly in a remote region of the Amazon rainforest last year.",
    "Researchers published their surprising findings in a prestigious international scientific journal early last month.",
    "Archaeologists unearthed ancient artifacts dating back at least five thousand years near the eroding riverbank.",
    "Astronomers detected a previously unknown exoplanet orbiting a distant star using the new space telescope.",
    "Geologists examined rock formations carefully to determine the geological age of the entire mountain range.",
    "Marine biologists studied the coral reef ecosystem extensively in the warm tropical waters off the island.",
    "Paleontologists found fossilized remains of a previously unknown dinosaur species in the eroded cliff face.",
    "The research team conducted a large study involving thousands of participants across several different continents.",
    "Chemists synthesized a new compound with potentially important medical applications for treating several rare diseases.",
    "Physicists conducted a series of experiments to verify the predictions of the controversial new theoretical model.",
    "Linguists analyzed the grammatical structure of the newly documented language spoken in the mountain villages.",
    "The laboratory technicians calibrated the sensitive instruments carefully to ensure accurate measurements for the experiment.",
    "Biologists tracked the declining population of endangered tigers across several national parks in southern Asia.",
    "The space agency successfully launched a new earth observation satellite into a polar orbit this morning.",
    "Engineers tested the aircraft prototype extensively before beginning any mass production of the production design.",
    "The double-blind trial minimized the risk of experimenter bias in the clinical drug evaluation study significantly.",
    "Researchers investigated the curious phenomenon extensively over the course of several years of careful fieldwork.",
    "The pharmaceutical company announced a significant breakthrough in treatments for a previously incurable rare disease.",
    "The gene therapy trial showed promising results in patients with the rare inherited blood disorder.",
    "Climatologists predicted continued warming trends based on extensive modeling of global atmospheric carbon data.",
    "Nuclear physicists observed the decay patterns of exotic isotopes produced in the large particle collider experiments.",
    "The neuroscience team mapped the connections between different regions of the brain using advanced imaging technology.",
    "Biochemists identified the specific enzyme responsible for breaking down the pollutant into entirely harmless compounds.",
    "The telescope captured the first detailed images of a black hole at the center of a galaxy.",
    "Materials scientists developed a new alloy that was both lighter and stronger than existing industrial steels.",
    "The study concluded that regular exercise substantially reduces the risk of developing serious cardiovascular disease.",
    "Researchers used advanced sequencing techniques to map the complete genome of the critically endangered species.",
    "The robotics team demonstrated a new prototype capable of performing delicate surgical tasks autonomously.",
    "Astronomers observed the spectacular transit of the planet across the face of its parent star.",
    "The climate model predicted significant changes to regional precipitation patterns over the coming several decades.",
    "Quantum computing researchers achieved a new milestone in error correction for superconducting qubits this quarter.",
    "The team analyzed thousands of ice core samples to reconstruct ancient climate conditions in remarkable detail.",
    "Botanists identified several rare plant species growing along the banks of the remote highland mountain river.",
    "The particle accelerator revealed unexpected patterns in the data collected during the long experimental run yesterday.",
    "Ornithologists banded hundreds of migratory songbirds to track their seasonal travel patterns across the continents.",
    "The deep sea expedition documented dozens of species never before seen by scientific investigators anywhere.",
    "Researchers developed a promising vaccine candidate that showed strong efficacy in the preliminary animal trials.",
    "Computer scientists designed a novel algorithm that solved the difficult optimization problem far more efficiently.",
    "Geneticists traced the lineage of the population back to a small founding group from central Africa.",
    "The seismographic network detected a swarm of small earthquakes beneath the previously dormant volcanic region.",
    "The scientific committee reviewed the methodology and recommended several important revisions before publication last week.",
    "Anthropologists documented cultural traditions of indigenous communities before the knowledge could be lost forever.",
    "The experiment yielded unexpected results that challenged the fundamental assumptions of the existing theoretical model entirely.",
    "Chemical engineers scaled up the production process from the laboratory bench to the industrial manufacturing facility.",
    "The expedition team collected samples from the remote glacier for subsequent analysis in the home laboratory.",
    "Biologists catalogued dozens of insect species previously unknown to science in the cloud forest canopy.",
    "The physics department acquired a state-of-the-art electron microscope for detailed structural analysis of new materials.",
    "Researchers monitored the eruption remotely using seismic instruments and thermal infrared satellite imagery throughout the morning.",
    "The statistical analysis confirmed that the observed effect was highly significant at the conventional scientific threshold.",
    "The research findings have important implications for the future development of next-generation energy storage technology.",
    # Medicine, health (100-129)
    "Doctors recommended regular exercise and a balanced diet to reduce the risk of chronic cardiovascular disease.",
    "The surgeon performed a delicate operation that lasted over six hours in the quiet operating room.",
    "The veterinarian treated the injured horse and predicted a full recovery within a few short weeks.",
    "Nurses monitored the critically ill patient closely throughout the long overnight shift in the intensive care unit.",
    "The radiologist detected a small abnormality on the scan that required further diagnostic investigation next week.",
    "Pediatricians urged parents to ensure their children received all recommended childhood vaccinations on the standard schedule.",
    "The cardiologist adjusted the medication dosage after carefully reviewing the patient latest laboratory test results.",
    "Emergency room staff stabilized the accident victim quickly before transferring him to the regional trauma center.",
    "Paramedics administered critical first aid at the accident scene before the ambulance arrived at the hospital.",
    "The dental hygienist carefully cleaned the patient teeth and scheduled the follow-up appointment for the spring.",
    "Physical therapists helped the stroke patient regain mobility through several months of intensive rehabilitation sessions.",
    "The oncology team developed a personalized treatment plan based on the detailed tumor genetic profile results.",
    "Pharmacists dispensed medications and provided clear guidance on proper dosage and potential side effects daily.",
    "The psychiatrist recommended both cognitive therapy and medication for the patient persistent anxiety condition management.",
    "Obstetricians delivered the healthy twin babies via emergency cesarean section early on Tuesday morning.",
    "The anesthesiologist carefully monitored the patient vital signs throughout the entire long surgical procedure yesterday.",
    "Public health officials launched a vaccination campaign in response to the rising case numbers statewide.",
    "The neurologist ordered additional tests to determine the underlying cause of the unexplained neurological symptoms.",
    "Dermatologists advised the use of sunscreen daily to reduce the risk of skin cancer development over time.",
    "The hospice team provided compassionate end-of-life care to families during the most difficult period.",
    "Ophthalmologists performed cataract surgery on hundreds of patients through the new free community outreach program.",
    "The geriatrician coordinated care across multiple medical specialists for the elderly patient complex chronic conditions.",
    "Endocrinologists helped patients manage their diabetes through careful diet medication and lifestyle modification strategies.",
    "The orthopedic surgeon replaced the damaged hip joint with a modern titanium prosthetic device successfully.",
    "Midwives supported the mother through a long labor that lasted well into the next morning.",
    "The epidemiologist traced the outbreak back to a single contaminated food source at the public event.",
    "Respiratory therapists helped the asthma patient develop a comprehensive management plan for his daily routine.",
    "The genetic counselor explained the complicated test results to the family in clear understandable language.",
    "Nutritionists recommended increasing the intake of fresh fruits and vegetables daily to improve overall health.",
    "The mental health counselor scheduled weekly therapy sessions with the patient to address ongoing depression symptoms.",
    # History, archaeology (130-159)
    "The ancient library contained thousands of rare manuscripts and scrolls preserved for over a thousand years.",
    "Historians discovered new documents shedding light on the ancient civilization that once ruled the entire region.",
    "The medieval castle stood on a rocky hill overlooking the fertile valley and the winding river below.",
    "Archaeologists carefully brushed sand from the newly exposed stone tablet covered in hieroglyphic inscriptions.",
    "The Roman amphitheater could once seat over fifteen thousand spectators for elaborate gladiatorial contests.",
    "Explorers discovered the lost city deep in the thick jungle after months of arduous searching.",
    "The Viking ship had been remarkably preserved in the peat bog for nearly a full thousand years.",
    "Ancient Egyptians built massive pyramids using construction techniques that modern engineers still find deeply impressive.",
    "The Silk Road connected distant civilizations and facilitated the exchange of goods ideas and religions for centuries.",
    "Colonial settlers faced enormous hardships during their first brutal winter in the newly founded coastal settlement.",
    "The Industrial Revolution transformed every aspect of society from agriculture to transportation to urban daily life.",
    "Byzantine mosaics covered the interior walls of the old cathedral in stunning images of religious figures.",
    "The Mongol Empire at its greatest extent stretched from Korea all the way to parts of Eastern Europe.",
    "Native American tribes developed sophisticated agricultural techniques long before European colonists ever arrived in the region.",
    "The French Revolution fundamentally altered political thought across Europe and the broader western world for decades.",
    "Ancient Greek philosophers laid the intellectual foundation for much of modern science and logical reasoning today.",
    "The Great Wall of China was constructed in stages over the course of nearly two thousand years.",
    "Medieval monks preserved countless classical texts through careful copying in monastic scriptoriums across Europe for centuries.",
    "The Aztec capital was one of the largest and most sophisticated cities in the entire world at its peak.",
    "Prehistoric cave paintings depicted animals and hunting scenes with remarkable artistic skill and striking detail.",
    "The Renaissance period witnessed an extraordinary flowering of art science and humanistic thought in northern Italy.",
    "Ancient Mesopotamia is often considered the birthplace of writing law and organized urban civilization.",
    "The discovery of the royal tomb stunned the archaeological community and generated worldwide public excitement immediately.",
    "Pioneer wagon trains traveled the dangerous Oregon Trail for months on their long journey west.",
    "The Ottoman Empire controlled vast territories across three continents for over six continuous centuries.",
    "Prehistoric peoples crossed the Bering land bridge and eventually populated the entire western hemisphere over time.",
    "The Black Death killed nearly a third of the population of medieval Europe within just a few years.",
    "Japanese samurai warriors followed a strict code of honor that shaped their behavior in virtually all situations.",
    "The invention of the printing press in the fifteenth century revolutionized the spread of knowledge everywhere.",
    "Ancient Greek and Roman authors composed epic poems that continue to influence literature and culture to this day.",
    # Arts, music, literature (160-199)
    "The orchestra performed a stunning rendition of the classical symphony to a capacity audience on Saturday evening.",
    "The artist displayed her striking new paintings at the downtown gallery opening on Friday evening last week.",
    "The novelist spent three years writing her latest bestselling book about immigrant life in early America.",
    "The choir sang beautiful harmonies during the annual holiday concert at the historic cathedral downtown last night.",
    "Photographers captured stunning images of the total solar eclipse from atop the isolated desert mountain hilltop.",
    "Musicians rehearsed intensively for weeks before the opening night of the international concert tour began.",
    "Dancers performed a breathtaking routine at the multicultural festival in the downtown city park last Saturday.",
    "The editor reviewed the submitted manuscript carefully and suggested several substantive revisions for the next draft.",
    "Painters gathered at the seaside to capture the shifting light on the waves at different times of day.",
    "The sculptor chiseled the large block of marble for months to reveal the figure hidden within it.",
    "Theater companies performed classic Shakespearean plays at the outdoor summer festival for over two full decades.",
    "The poet read her work aloud at the small bookshop to an enthusiastic group of local fans.",
    "Jazz musicians improvised through the late night at the dimly lit club in the historic neighborhood.",
    "The film director spent two years editing the documentary about the endangered coastal fishing communities.",
    "Novelists often find inspiration in the ordinary details of everyday life and personal human relationships.",
    "The ballet company performed the classical production to sold-out crowds for nearly a month straight.",
    "Street artists transformed the gray concrete walls of the old warehouse district into vibrant colorful murals.",
    "The pianist gave an emotional performance of the sonata that moved much of the audience to tears.",
    "Opera singers trained for many years to develop the vocal stamina needed for demanding lead roles.",
    "The calligrapher carefully inscribed the names on the graduation certificates in elegant hand-drawn cursive script.",
    "Documentary filmmakers spent months in the Arctic documenting the effects of climate change on local communities.",
    "The literary critic praised the novel for its unflinching honesty and remarkable stylistic innovation throughout.",
    "Children learned traditional folk songs passed down through generations at the annual community summer music camp.",
    "The harpist played quiet background music throughout the wedding reception to create an elegant atmosphere.",
    "Pottery students worked at the wheel learning traditional techniques from the master craftsman who taught there.",
    "The acting troupe performed improvised comedy shows at the small basement venue on Friday nights each week.",
    "Glassblowers demonstrated their traditional craft to visitors at the historic workshop on the busy harbor.",
    "The string quartet played chamber music in the intimate setting of the private gallery recital yesterday.",
    "Printmakers pulled limited edition etchings using a large antique press carefully restored earlier that same year.",
    "The animator spent countless hours drawing each individual frame for the award-winning animated short film.",
    "Storytellers gathered around the campfire to share traditional folk tales with the rapt audience of children.",
    "The composer premiered his latest symphony with the philharmonic to critical acclaim just last weekend.",
    "Poets exchanged their latest work at the monthly reading held upstairs at the downtown independent bookstore.",
    "The muralist completed an enormous piece on the library exterior wall depicting local history and culture.",
    "Book club members debated the novel ending passionately over coffee and pastries on that Sunday afternoon.",
    "The actor prepared for the demanding role by spending several weeks with people in similar circumstances.",
    "Graphic designers created striking visual identities for the new cultural festival and its promotional materials.",
    "The violinist performed a solo recital of works by Bach and Paganini at the old concert hall.",
    "Comic book artists shared their creative process with eager fans at the annual industry convention last weekend.",
    "The playwright workshopped her new drama with actors before the official public premiere next month.",
    # Sports (200-229)
    "Swimmers competed fiercely for the gold medal at the national championship in the olympic pool yesterday.",
    "Athletes trained intensively for months leading up to the international competition scheduled for the coming summer.",
    "The coach motivated the young team with an encouraging speech before the championship final game began.",
    "Mountain climbers reached the summit of the peak after five grueling days of difficult technical ascent.",
    "The marathon runner maintained a remarkably steady pace for the entire twenty-six mile certified course.",
    "Soccer players kicked the ball across the field during the crucial playoff match last weekend evening.",
    "The gymnast performed a flawless routine on the balance beam to earn the highest possible competition score.",
    "Tennis professionals competed in the grand slam tournament for several long weeks each summer season.",
    "The golf course hosted the major championship for the third consecutive year this summer.",
    "Cyclists pedaled up the steep mountain pass during the most grueling stage of the race.",
    "The hockey team celebrated their overtime victory in the packed arena after the final buzzer sounded.",
    "Baseball fans filled the stadium for the opening game of the new regular season last Tuesday.",
    "The boxer trained in the gym every morning before sunrise for the upcoming title fight.",
    "Skiers descended the challenging black diamond trail in the fresh powder on the mountain this morning.",
    "The rowing team synchronized their strokes perfectly to move the sleek boat swiftly down the river.",
    "Wrestlers practiced their moves daily at the training facility in preparation for the regional tournament weekend.",
    "The sprinter crossed the finish line well ahead of the pack in a new personal record time.",
    "Surfers rode the massive waves at the famous break during the annual international surfing competition.",
    "The basketball team huddled during the crucial final timeout to plan their last play carefully.",
    "Rugby players scrummed in the thick mud during the championship match despite the pouring cold rain.",
    "The volleyball team spiked the ball repeatedly to score important points in the tight final match.",
    "Hikers followed the winding trail through the dense forest to the spectacular waterfall at the end.",
    "The race car driver navigated the hairpin turn at tremendous speed during the grand prix race.",
    "Figure skaters glided across the ice performing their elegant routines in the brand new uniforms.",
    "The coach diagrammed the next play on the whiteboard during the brief team strategy session.",
    "Runners stretched carefully before the race to prevent any injury during the long distance running event.",
    "The quarterback threw a perfect pass downfield for the winning touchdown in the final few seconds.",
    "Sailors navigated through rough seas during the overnight crossing to the remote offshore island destination.",
    "The equestrian trained her horse for the upcoming dressage competition at the regional annual event.",
    "Track athletes competed in field events throughout the afternoon at the multi-school invitational meet.",
    # Food, cooking (230-259)
    "The renowned chef prepared an elaborate feast for the visiting foreign dignitaries on Saturday evening last week.",
    "Farmers markets offer fresh seasonal produce directly from local growers every Saturday and Sunday morning.",
    "The bakery produces fresh bread and pastries every single morning before the sun rises over town.",
    "Local farmers harvested their crops carefully before the first killing frost arrived this early autumn.",
    "The coffee shop on the corner opens at five each morning to serve the early commuters.",
    "The family gathered around the long dinner table to enjoy the traditional holiday feast together.",
    "Restaurants along the waterfront served fresh seafood caught earlier that same morning by local fishermen.",
    "The wine bar featured carefully chosen selections from small vineyards in the nearby valley each month.",
    "Home cooks exchanged treasured recipes at the monthly cooking club meeting at the community center.",
    "The pastry chef decorated elaborate wedding cakes for the busy weekend events throughout the summer season.",
    "Brewers experimented with unusual ingredients to create distinctive small-batch craft beers in the local brewery.",
    "The sushi chef sliced the fresh tuna with precision learned over decades of dedicated careful practice.",
    "Food trucks gathered in the downtown park each Thursday evening offering a wide variety of cuisines.",
    "The ice cream shop on Main Street handcrafts new flavors using seasonal fruits from nearby local farms.",
    "Grill masters tended the slow-cooking brisket for twelve hours at the annual summer barbecue competition downtown.",
    "The cheese shop displayed over a hundred varieties from artisan dairies across the country and abroad.",
    "Tea houses served delicate pastries alongside carefully brewed imported Asian teas each weekday afternoon.",
    "The pizza restaurant uses a wood-fired oven to produce authentic Italian-style pies for its discerning customers.",
    "Chocolatiers crafted handmade truffles using single-origin cocoa beans from a particular small South American farm.",
    "The sandwich shop on the square serves the best lunch in town according to nearly everyone.",
    "Vineyards across the region hosted several tasting events during the autumn harvest festival last weekend.",
    "The butcher prepared custom cuts of grass-fed beef for the upcoming dinner party at the estate.",
    "Food critics raved about the inventive new restaurant that recently opened in the downtown arts district.",
    "The farmer delivered freshly picked strawberries to the restaurants on his daily route every single morning.",
    "Culinary students practiced knife skills under the watchful eye of the master chef in the bright kitchen.",
    "The diner has served the same secret pancake recipe since it first opened back in 1952.",
    "Brewpubs offered seasonal beers paired with dishes that complemented their specific flavor profiles perfectly.",
    "The ramen shop attracted long lines of hungry customers most nights of the busy week.",
    "Pastry shops around the city specialized in French croissants and other traditional European baked goods.",
    "The catering company prepared meals for several hundred guests at the large outdoor wedding reception.",
    # Travel, geography (260-289)
    "Tourists explored the ancient ruins and marveled at the intricate stone carvings that covered the exterior walls.",
    "The pilot navigated the aircraft through turbulent weather conditions safely to the destination international airport.",
    "The train departed from the central station exactly on schedule this clear cold winter morning.",
    "Travelers gathered at the terminal gate waiting for the delayed international flight to finally board.",
    "The cruise ship docked at the tropical island for a scheduled day of passenger shore excursions.",
    "Backpackers hiked the famous trail for three weeks to reach the distant remote summit camp.",
    "The hotel concierge recommended several excellent local restaurants to the weary visitors arriving late that night.",
    "Visitors toured the historic battlefield site with the knowledgeable ranger guide on the morning weekend tour.",
    "The family rented a small cabin near the lake for their annual two-week summer vacation trip.",
    "Business travelers filled the airport lounge during the unexpected weather delay early Tuesday afternoon.",
    "The guidebook described the best viewpoints along the scenic coastal drive in remarkable great detail.",
    "Tourists photographed the spectacular waterfall from the newly built observation deck on the high cliff edge.",
    "The ferry crossed the harbor every twenty minutes during the busy morning rush hour commute.",
    "Visitors wandered through the crowded open-air market buying unique souvenirs and beautiful local handicrafts.",
    "The travel agent booked the complicated multi-city itinerary for the elaborate retirement celebration tour.",
    "Hikers followed the well-marked trail through the national park to the historic fire lookout tower.",
    "The bus driver followed the scheduled detour after the main highway was closed for construction.",
    "Travelers exchanged currency at the bank before continuing their long journey across the international border.",
    "The country inn offered charming rooms and home-cooked breakfast to guests exploring the rural countryside.",
    "Scuba divers explored the colorful coral reef during the morning excursion off the quiet island coast.",
    "The ski resort opened early this year due to heavy snowfall in the surrounding mountains above.",
    "Travelers consulted their phones for directions while navigating the confusing historic city center today.",
    "The bed and breakfast welcomed guests warmly throughout the peak autumn foliage viewing season.",
    "Visitors toured the famous botanical gardens and learned about rare endangered plants from the volunteer guides.",
    "The tour bus followed a carefully planned route through the most picturesque of the countryside villages.",
    "Adventurers rafted the white water river with experienced guides during the height of the summer season.",
    "The airport shuttle transported passengers between the distant parking lots and the busy terminal building.",
    "Tourists lined up for hours to climb the famous bell tower for panoramic city views.",
    "The expedition team prepared carefully for weeks before departing to study the remote polar region.",
    "Visitors sampled local wines at a series of tastings organized throughout the annual vineyard festival.",
    # Business, finance, economics (290-319)
    "The accountant prepared the annual financial statements carefully for the upcoming board of directors review.",
    "The stock market experienced significant volatility last week as investors reacted to the gloomy economic report.",
    "The company reported record quarterly earnings driven by strong international sales across every single division.",
    "Consumer confidence rose sharply according to the latest national economic survey released yesterday afternoon.",
    "The central bank raised interest rates for the third consecutive quarter citing persistent inflation concerns.",
    "Unemployment figures dropped to their lowest level in a full decade according to Friday jobs report.",
    "Economists predicted moderate growth for the national economy in the coming fiscal quarter this year.",
    "The tax auditor reviewed the corporation financial records carefully for any discrepancies or irregularities.",
    "The diplomat negotiated a new trade agreement between the two neighboring countries over several long months.",
    "The manager implemented new workplace policies to improve productivity and employee morale throughout the company.",
    "Analysts reviewed the performance metrics carefully for the previous fiscal quarter before the earnings call began.",
    "The marketing team launched a new advertising campaign targeting younger consumers in several major urban markets.",
    "Small business owners gathered at the chamber of commerce for the monthly networking breakfast meeting.",
    "The venture capital firm invested in three promising technology startups earlier this calendar year.",
    "Retail sales exceeded expectations during the critical holiday shopping season this past December.",
    "The human resources department scheduled training sessions for all new employees hired last month.",
    "The merger between the two large companies was announced after many months of careful negotiation.",
    "Supply chain managers worked to resolve the disruptions caused by the extreme weather events.",
    "The board of directors voted unanimously to approve the expansion plans at the annual shareholder meeting.",
    "Auditors completed their independent review of the large nonprofit finances before the reporting deadline arrived.",
    "The commercial real estate market showed signs of recovery after the long pandemic-induced slump.",
    "Traders worked long hours on the crowded exchange floor during the recent period of high market volatility.",
    "The credit union offered favorable mortgage rates to first-time home buyers throughout the summer promotional period.",
    "Consultants advised the struggling company on strategies for restructuring its operations and reducing operating costs.",
    "The insurance adjuster inspected the significant property damage caused by the recent severe hailstorm carefully.",
    "Bankers approved the small business loan after reviewing several years of tax returns and financial statements.",
    "The entrepreneur pitched her innovative business idea to potential investors at the technology conference last weekend.",
    "Shareholders expressed their concerns during the lengthy annual general meeting held last Thursday afternoon.",
    "The corporation announced a major restructuring plan affecting thousands of employees across multiple different divisions.",
    "Economic analysts debated the impact of the new trade policies on the domestic manufacturing sector.",
    # Law, government, politics (320-349)
    "The lawyer presented compelling arguments in defense of her client during the lengthy criminal trial.",
    "The judge delivered the verdict after careful deliberation with the jury over many days of testimony.",
    "The governor signed the important new legislation into law during a public ceremony this morning.",
    "The president addressed the nation in a televised speech focusing on the pressing current economic situation.",
    "The election results were certified after a thorough recount of every single disputed provisional ballot.",
    "International observers monitored the democratic election process closely throughout the voting and counting periods.",
    "The court ruled that the controversial regulation exceeded the statutory authority granted to the federal agency.",
    "The peace accord was signed after several months of difficult and often extremely tense negotiations.",
    "The regulatory agency issued new safety guidelines affecting manufacturers across the entire automotive industry.",
    "The mayor announced ambitious plans to renovate the historic downtown district over the next five years.",
    "The journalist investigated persistent allegations of corruption within the large multinational organization for months.",
    "The diplomat met with foreign officials to resolve the ongoing border dispute peacefully this week.",
    "The city council approved the new zoning ordinance after a contentious public hearing last Tuesday evening.",
    "The legislative committee held hearings on the proposed reform bill for several days last week.",
    "The senator introduced the amendment during the floor debate on the major new infrastructure legislation yesterday.",
    "The department investigated the formal complaint thoroughly before issuing its detailed final report to the public.",
    "The ambassador was formally recalled after diplomatic relations deteriorated significantly over the past three months.",
    "The court clerk filed the important legal documents before the five oclock closing deadline on Friday.",
    "The public defender represented the indigent client during the preliminary hearing in county criminal court.",
    "The bill passed both chambers of the state legislature with overwhelming bipartisan majority support this week.",
    "The prosecutor presented the physical evidence carefully to the grand jury during the closed afternoon session.",
    "The attorney general launched a formal investigation into the alleged financial fraud at the local nonprofit.",
    "The police officer filed the complete incident report before the end of his long night shift.",
    "The tribunal heard testimony from dozens of witnesses over the course of the three week proceedings.",
    "The parliament passed emergency legislation in response to the rapidly unfolding national public health crisis.",
    "The plaintiff filed the lawsuit alleging breach of contract against the large regional construction company.",
    "The defendant entered a plea of not guilty at the arraignment proceeding earlier today at the courthouse.",
    "The attorney drafted the detailed settlement agreement after hours of intensive negotiations with opposing counsel.",
    "The court of appeals overturned the lower court ruling after reviewing the case file thoroughly.",
    "The sheriff deputies patrolled the rural county roads throughout the unusually quiet holiday weekend.",
    # Education (350-379)
    "Students gathered in the auditorium for the annual awards ceremony later that busy Friday afternoon.",
    "The school principal addressed concerned parents at the meeting about recent changes to student safety policies.",
    "The teacher explained the complex mathematical concept using practical real-world examples the class could easily understand.",
    "The professor delivered an inspiring lecture on quantum mechanics to the engaged undergraduate students last Wednesday.",
    "The librarian organized the extensive new collection of books by author genre and subject area.",
    "The tutor helped struggling students prepare for the upcoming standardized college entrance examinations this spring.",
    "Graduate students presented their thesis research at the department annual symposium last Friday afternoon.",
    "The kindergarten teacher read an engaging picture book to the enthusiastic children after their lunch break.",
    "Classroom assistants helped young students with reading comprehension exercises each Tuesday and Thursday afternoon.",
    "The chess club met in the school library every Wednesday after classes to practice together.",
    "Science fair projects filled the large school gymnasium for the annual district-wide competition this weekend.",
    "The debate team prepared arguments for the upcoming regional championship tournament held in another nearby city.",
    "Field trip chaperones accompanied the fifth graders to the natural history museum downtown on Tuesday morning.",
    "The orchestra conductor led students through long rehearsals for the upcoming spring concert on Saturday evening.",
    "Academic advisors met with juniors to review their graduation requirements and course planning options carefully.",
    "The honor society inducted new members during the special evening ceremony in the school auditorium.",
    "Students studied intensively for their final examinations in the quiet university library every evening this week.",
    "The physical education instructor organized intramural sports tournaments during the final weeks of the semester.",
    "Research assistants collected data for the professor long-term study across several undergraduate student populations.",
    "The art teacher displayed student work in the school hallway before parent-teacher conferences on Friday evening.",
    "College counselors helped seniors complete applications for their top-choice universities by the upcoming deadline.",
    "The drama club performed the fall musical on three consecutive evenings in the school theater auditorium.",
    "Writing workshop participants exchanged helpful feedback on their short story drafts each Thursday evening this term.",
    "The math team qualified for the state championship after placing first in the regional tournament.",
    "Teachers attended the professional development conference during the district in-service training day last Monday.",
    "The guidance counselor spoke with each senior student individually about their specific post-graduation plans carefully.",
    "Classroom volunteers read weekly with struggling students as part of the literacy support program.",
    "The university launched a new scholarship program for first-generation college students this academic year.",
    "Student government representatives discussed campus issues with administrators at the monthly meeting on Wednesday afternoon.",
    "The foreign language department hosted a cultural festival celebrating the diversity of its student body beautifully.",
    # Construction, engineering (380-409)
    "Construction workers completed the foundation of the new office building well ahead of the original schedule.",
    "Engineers designed a new bridge that could withstand severe earthquakes and other significant seismic events.",
    "The architect presented detailed blueprints for the new community recreation center to the planning commission.",
    "Electricians installed new wiring throughout the extensively renovated downtown office building over the past month.",
    "The plumber repaired the major leak underneath the kitchen sink before the tenants arrived that afternoon.",
    "The carpenter crafted beautiful custom furniture using traditional woodworking techniques passed down through his family.",
    "Workers assembled the temporary stage equipment for the outdoor summer music festival this coming weekend.",
    "The contractor estimated the total cost of the home renovation project accurately within one percent.",
    "The welder joined heavy metal beams together to form the structural framework of the new warehouse building.",
    "Crews poured the reinforced concrete foundation for the new community sports center on Tuesday morning.",
    "Roofers worked carefully on the steep pitched roof of the large Victorian-era home downtown.",
    "The surveyor marked the exact property boundaries using the precision GPS equipment provided by the firm.",
    "Inspectors examined the newly completed construction for code compliance before final occupancy permits were issued.",
    "The crane operator lifted the massive steel girder into position on the top floor of the new tower.",
    "Glaziers installed the floor-to-ceiling windows throughout the spacious new glass-fronted corporate office tower.",
    "The demolition crew brought down the abandoned old factory building in a carefully controlled manner.",
    "Landscape architects designed the sprawling new campus with extensive green space and beautiful walking paths.",
    "The structural engineer analyzed the building foundation problems before recommending appropriate repair solutions to management.",
    "Masons laid the intricate brick facade of the newly restored historic courthouse over several long weeks.",
    "The excavator operator dug the deep foundation trenches for the new three-story apartment complex building.",
    "Pipefitters installed the extensive plumbing system throughout the newly constructed five-story hospital wing carefully.",
    "The site manager coordinated multiple crews working simultaneously on different areas of the large construction project.",
    "HVAC technicians installed the modern climate control system in the newly built school auditorium efficiently.",
    "The concrete mixer arrived early to deliver the foundation material for the new apartment complex downtown.",
    "Drywallers finished the interior walls carefully throughout the sprawling suburban new home development this spring.",
    "The insulation crew worked efficiently to meet the energy efficiency requirements of the new building codes.",
    "Painters applied two coats of high-quality paint to every room in the fully restored historic mansion.",
    "The tile setter installed intricate mosaic patterns on the floor of the ornate new hotel lobby.",
    "Ironworkers assembled the complex steel skeleton of the new skyscraper over the course of many long months.",
    "The project manager adjusted the tight schedule to accommodate the unexpected delay caused by inclement weather.",
    # Daily life, family (410-439)
    "Children played happily in the park while their parents watched carefully from nearby benches in the shade.",
    "Gardeners planted colorful flowers along the pathway leading to the front entrance of the apartment building.",
    "Volunteers worked tirelessly to clean up the long beach after the particularly severe tropical storm last week.",
    "The old lighthouse had guided ships safely through the narrow strait for several long centuries.",
    "The mechanic diagnosed the engine problem carefully and ordered the replacement parts immediately on Tuesday morning.",
    "The janitor maintained the large building in excellent condition throughout the entire academic school year.",
    "The locksmith replaced all the exterior locks in the apartment building for improved overall security.",
    "The seamstress repaired the vintage wedding gown using original fabric and traditional hand sewing techniques.",
    "The tailor carefully altered the wool suit to fit the customer perfectly for his upcoming wedding.",
    "The watchmaker disassembled the antique timepiece to replace the worn internal gears and springs carefully.",
    "The florist arranged beautiful bouquets for the reception at the grand harbor hotel ballroom on Friday.",
    "The dog walker took several energetic dogs through the neighborhood park every morning before breakfast time.",
    "Grandparents took the grandchildren fishing at the small pond behind the old family cabin this weekend.",
    "The delivery driver dropped off packages throughout the quiet residential neighborhood on Saturday morning today.",
    "Neighbors gathered for a potluck dinner at the community center on the last Sunday of the month.",
    "The retiree spent most mornings at the local coffee shop reading the newspaper with friends.",
    "The babysitter watched the children carefully while their parents attended the formal dinner downtown on Saturday.",
    "The young family moved into the charming old house on the quiet tree-lined street last month.",
    "The handyman repaired the broken garden gate latch before dinner on Sunday afternoon last weekend.",
    "The postal carrier delivered mail along the same rural route for over twenty-five consecutive years.",
    "The grocery store clerk helped the elderly woman carry her heavy bags out to her car.",
    "The dry cleaner returned the meticulously cleaned garments on the following Thursday afternoon as promised earlier.",
    "The babysitter organized a small birthday party for the twins on a rainy Saturday afternoon this spring.",
    "The parent volunteers decorated the classroom for the upcoming holiday party at the elementary school.",
    "The siblings argued over whose turn it was to set the dinner table before the meal.",
    "The newlyweds painted every room in their small starter home before moving in last month.",
    "The elderly couple sat on the front porch watching the sun set slowly over the distant hills.",
    "The garage sale attracted dozens of bargain hunters on Saturday morning despite the overcast gray skies.",
    "The family adopted a rescue dog from the local animal shelter over the long holiday weekend.",
    "The homeowners redesigned the backyard garden carefully to attract more butterflies and native songbirds each spring.",
    # Space, astronomy (440-454)
    "Astronomers used powerful telescopes to observe the distant galaxy in remarkable unprecedented detail for the first time.",
    "The space agency planned a crewed mission to the moon for late next decade with international partners.",
    "Satellites orbiting the earth provide continuous communications coverage across the entire populated globe today.",
    "The international space station completed its eighteen-thousandth orbit around the earth yesterday morning.",
    "Astronauts conducted an extended spacewalk to perform scheduled maintenance on the exterior of the station.",
    "The rover transmitted high-resolution images of the Martian surface back to mission control engineers on earth.",
    "Astronomers detected gravitational waves from the merger of two distant neutron stars last Tuesday evening.",
    "The space telescope captured stunning images of nebulae thousands of light-years away from our home planet.",
    "Solar panels powered the satellite continuously during the slow orbital period around the small nearby moon.",
    "The deep space probe transmitted its final signal after traveling for nearly forty years through space.",
    "Engineers monitored the trajectory of the spacecraft during its approach to the target asteroid carefully.",
    "The observatory high on the mountain captured images of the distant supernova the previous night.",
    "Astronomers calculated the precise orbit of the newly discovered comet using six months of observations.",
    "Radio telescopes detected unusual signals originating from the direction of the spiral galaxy last week.",
    "The lunar mission carried experiments designed to study the radiation environment on the surface closely.",
    # Ocean, marine (455-469)
    "Marine biologists studied the rare deep sea vents that support unique extremophile microbial ecosystems.",
    "The research submarine explored the ocean floor at depths far beyond the reach of any sunlight.",
    "Whale researchers tracked the annual migration of humpbacks from tropical breeding grounds to polar feeding areas.",
    "The research vessel sailed for three months documenting the biodiversity of the remote southern ocean waters.",
    "Oceanographers measured currents and temperatures throughout the north Atlantic during the long summer research expedition.",
    "The lighthouse keeper maintained the historic beacon that had guided ships for over a full century.",
    "Port authorities coordinated the movement of dozens of massive container ships through the busy harbor daily.",
    "The fishing fleet returned to port with their heavy catch just before the storm made landfall.",
    "Lifeguards patrolled the busy summer beach rescuing several swimmers caught in the strong dangerous rip currents.",
    "The container ship navigated through the narrow canal under the guidance of the experienced local pilot.",
    "Divers explored the sunken ship resting on the ocean floor near the remote coral reef.",
    "The oceanographer deployed autonomous buoys to measure wave heights during the approaching tropical storm system.",
    "Marine ecologists counted juvenile fish populations among the sea grass beds in the shallow coastal estuary.",
    "The harbor master coordinated tugboat operations throughout the busy morning as the cargo ships arrived.",
    "Coast guard crews rescued the stranded sailors from their disabled vessel late on Thursday evening.",
    # Transportation (470-484)
    "Commuters packed the subway train during the busy morning rush toward the downtown business district.",
    "The airline announced several new nonstop routes to popular European destinations starting next summer season.",
    "Freight trains crossed the country delivering massive tonnages of agricultural goods from farms to distant market cities.",
    "The bus system expanded service to underserved neighborhoods after the successful voter-approved funding measure finally passed.",
    "The ride-share driver navigated the busy downtown streets during the heavy evening rush hour traffic.",
    "Truck drivers hauled heavy shipments of lumber from the Pacific Northwest to cities on the east coast.",
    "The ferry connected the island community to the mainland with several scheduled crossings each day.",
    "High-speed rail lines reduced travel times between major cities across the densely populated eastern region.",
    "The airport expanded its international terminal to handle growing volumes of intercontinental passenger traffic.",
    "Delivery drones completed short-range package deliveries across the suburban pilot test area earlier this year.",
    "The bicycle courier navigated congested city traffic to deliver urgent documents across town quickly each afternoon.",
    "Cargo ships queued outside the port waiting for berths during the unusually heavy import season.",
    "The commuter rail authority added new carriages to accommodate growing ridership on weekday morning routes.",
    "Long-haul truckers stopped overnight at the highway rest areas during their cross-country delivery runs.",
    "The taxi dispatcher coordinated pickups across the city during the rainy rush hour last Tuesday evening.",
    # Agriculture, crafts (485-499)
    "Shepherds guided their flocks across the rolling hills toward the sheltered valley as evening approached quietly.",
    "The beekeeper harvested honey from the hives at the end of the busy summer pollination season.",
    "Orchards yielded a bumper crop of apples and pears after the long warm growing season this year.",
    "The dairy farmer milked the herd of cows twice each day year-round without exception in any weather.",
    "Winemakers crushed the grapes in late September to begin the lengthy fermentation process in the cellar.",
    "The ranch hands herded the cattle across miles of open range land during the spring roundup.",
    "Vegetable growers sold their seasonal produce at the popular farmers market every Saturday morning all summer.",
    "The goat farm produced artisanal cheeses aged in the cool stone cellar for several months.",
    "Tractors worked the expansive fields from dawn until dusk during the busy fall harvest season.",
    "The barn swallows nested in the eaves of the old red barn for several consecutive summers.",
    "Blacksmiths demonstrated the traditional craft at the annual heritage festival held last weekend downtown.",
    "The cooper assembled oak whiskey barrels at the small local distillery using centuries-old techniques passed down.",
    "Weavers created intricate tapestries on large wooden looms at the historic craft center downtown last month.",
    "The potter threw clay on the wheel shaping bowls and vases for the upcoming holiday craft show.",
    "Quilters gathered each Thursday evening to work together on the collaborative community quilt project downtown.",
]

assert len(SENTENCE_POOL) == 500, f"Pool size is {len(SENTENCE_POOL)}, expected 500"


def _split_at_ratio(sentence, ratio):
    """Split at the word boundary closest to the target ratio. Guarantees
    at least 2 words on each side."""
    words = sentence.split()
    n = len(words)
    pos = max(2, min(n - 2, round(n * ratio)))
    return " ".join(words[:pos]), " ".join(words[pos:])


# ═══════════════════════════════════════════════════════════════════════
#  LIKELY: mid-sentence splits — 500 sentences × 5 ratios = 2500 cases
# ═══════════════════════════════════════════════════════════════════════

_SPLIT_RATIOS = (0.3, 0.4, 0.5, 0.6, 0.7)

LIKELY_MID_SENTENCE = []
for _si, _sent in enumerate(SENTENCE_POOL):
    for _r in _SPLIT_RATIOS:
        _first, _second = _split_at_ratio(_sent, _r)
        LIKELY_MID_SENTENCE.append(
            (_first, _second, 0.5, f"midsent_{_si:03d}_r{int(_r * 100)}")
        )


# ═══════════════════════════════════════════════════════════════════════
#  LIKELY: mid-word / hyphenation breaks — bespoke hand-crafted pairs
# ═══════════════════════════════════════════════════════════════════════

_MIDWORD_PAIRS = [
    ("The committee discussed the hypothet", "ical scenario at length during the session", 0.5),
    ("The environ", "mental impact assessment was completed last week", 0.5),
    ("Scientists presented the experi", "mental results at the international conference", 0.5),
    ("The govern", "ment announced new regulations for the industry", 0.5),
    ("Researchers investigated the phe", "nomenon extensively over several years", 0.5),
    ("The inter", "national community responded swiftly to the crisis", 0.5),
    ("Officials reviewed the administr", "ative procedures for processing applications", 0.5),
    ("The organiz", "ational structure was reformed to improve efficiency", 0.5),
    ("Experts analyzed the communi", "cation breakdown between the two departments", 0.5),
    ("The represent", "ative presented the findings to the full assembly", 0.5),
    ("Detectives continued the investig", "ation into the series of incidents", 0.5),
    ("The approxim", "ately three hundred participants completed the survey", 0.5),
    ("Engineers improved the manufactur", "ing process to reduce waste significantly", 0.5),
    ("The determin", "ation of the committee was evident in their report", 0.5),
    ("Officials reformed the administr", "ation of public services in the region", 0.5),
    ("The recommend", "ation was accepted unanimously by the board members", 0.5),
    ("Teachers improved the understand", "ing of complex topics through visual aids", 0.5),
    ("The transport", "ation network was expanded to cover rural areas", 0.5),
    ("Critics described the perform", "ance as truly extraordinary and memorable", 0.5),
    ("The comprehens", "ive report covered every aspect of the situation", 0.5),
    ("Researchers made an archaeolog", "ical discovery near the ancient settlement", 0.5),
    ("The pharmaceut", "ical company announced a breakthrough treatment", 0.5),
    ("Therapists explored the psycholog", "ical factors contributing to the condition", 0.5),
    ("The constitut", "ional amendment was ratified by the required states", 0.5),
    ("Engineers developed new telecommuni", "cation systems for remote areas", 0.5),
    ("Scientists studied the electro", "magnetic properties of the new material", 0.5),
    ("Doctors monitored the cardio", "vascular health of patients in the trial", 0.5),
    ("Economists analyzed the socio", "economic impact of the trade agreement", 0.5),
    ("The inter", "disciplinary team collaborated on the research project", 0.5),
    ("The unpreced", "ented growth surprised all market analysts this quarter", 0.5),
    ("They modernized the metro", "politan transit system over five years", 0.5),
    ("The infra", "structure investment totaled several billion dollars", 0.5),
    ("Researchers in bio", "technology made significant advances this year", 0.5),
    ("The nano", "technology applications showed promising early results", 0.5),
    ("Engineers designed a new semi", "conductor chip with improved performance", 0.5),
    ("The micro", "processor architecture was redesigned from scratch", 0.5),
    ("Students studied thermo", "dynamics as part of the engineering curriculum", 0.5),
    ("Plants perform photo", "synthesis to convert sunlight into usable energy", 0.5),
    ("The neuro", "logical examination revealed no significant abnormalities", 0.5),
    ("The philo", "sophical debate continued well into the evening", 0.5),
    ("The anthropo", "logical study documented unique cultural practices", 0.5),
    ("The meteoro", "logical station recorded unusually high temperatures", 0.5),
    ("The oceano", "graphic expedition mapped the underwater terrain", 0.5),
    ("Scientists used crystallo", "graphy to determine the molecular structure", 0.5),
    ("The spectro", "scopy analysis confirmed the chemical composition", 0.5),
    ("The biblio", "graphy included over three hundred references", 0.5),
    ("The choreo", "grapher designed an innovative dance sequence", 0.5),
    ("The cinemato", "grapher captured stunning visual compositions", 0.5),
    ("The demo", "graphic analysis revealed shifting population trends", 0.5),
    ("The encyclo", "pedia contained entries on thousands of topics", 0.5),
    ("The philan", "thropic organization funded numerous community projects", 0.5),
    ("The seismo", "graph detected minor tremors throughout the region", 0.5),
    ("The profession", "al standards were updated to reflect current practices", 0.5),
    ("The technolog", "ical advancement transformed the entire industry", 0.5),
    ("The collabor", "ative effort produced remarkable results quickly", 0.5),
    ("The experiment", "al data confirmed the theoretical predictions", 0.5),
    ("Officials updated the regulat", "ory framework for financial institutions", 0.5),
    ("The document", "ation process was streamlined using new software", 0.5),
    ("The implement", "ation phase began after the planning was completed", 0.5),
    ("The educ", "ational program expanded to serve more students", 0.5),
    ("The transform", "ation of the company took nearly three years", 0.5),
    ("The inform", "ation was distributed to all relevant departments", 0.5),
    ("The confirm", "ation hearing lasted for several days in the senate", 0.5),
    ("The present", "ation included charts graphs and detailed analysis", 0.5),
    ("The conserv", "ation efforts helped protect the endangered habitat", 0.5),
    ("The observ", "ation tower provided panoramic views of the city", 0.5),
    ("The classific", "ation system was reorganized by the committee", 0.5),
    ("The certific", "ation process required passing multiple examinations", 0.5),
    ("The communic", "ation channels were improved across the organization", 0.5),
    ("The negoti", "ation between the parties lasted for several weeks", 0.5),
    ("The demonstr", "ation attracted thousands of participants downtown", 0.5),
    ("The examin", "ation results were published on the official website", 0.5),
    ("The explan", "ation provided by the expert clarified the issue", 0.5),
    ("The applic", "ation deadline was extended by two additional weeks", 0.5),
    ("The public", "ation received positive reviews from literary critics", 0.5),
    ("The found", "ation awarded grants to promising young researchers", 0.5),
    ("The instal", "lation of the new system took three full days", 0.5),
    ("The compens", "ation package included salary benefits and bonuses", 0.5),
    ("The prepar", "ation for the event required months of planning", 0.5),
    ("The cooper", "ation between agencies improved response times", 0.5),
    ("The integr", "ation of the two systems proved more complex than expected", 0.5),
    ("The restor", "ation of the historic building won an architecture award", 0.5),
]

LIKELY_MIDWORD = [
    (f, s, ms, f"midword_{i:03d}") for i, (f, s, ms) in enumerate(_MIDWORD_PAIRS)
]


# ═══════════════════════════════════════════════════════════════════════
#  UNLIKELY: pair unrelated sentences from the same pool
# ═══════════════════════════════════════════════════════════════════════
#
# For each sentence i, take its first half and pair it with the second
# half of sentence (i + OFFSET) % 500. OFFSET=251 is prime and coprime
# with 500, guaranteeing every sentence index is hit exactly once and
# the two halves come from topically distant regions of the pool.
# ═══════════════════════════════════════════════════════════════════════

_UNLIKELY_OFFSET = 251

_UNLIKELY_PAIRS = []
for _i in range(len(SENTENCE_POOL)):
    _j = (_i + _UNLIKELY_OFFSET) % len(SENTENCE_POOL)
    _first_half, _ = _split_at_ratio(SENTENCE_POOL[_i], 0.5)
    _, _second_half = _split_at_ratio(SENTENCE_POOL[_j], 0.5)
    _UNLIKELY_PAIRS.append(
        (_first_half, _second_half, 0.5, f"unrelated_{_i:03d}_x{_j:03d}")
    )


# ═══════════════════════════════════════════════════════════════════════
#  Combine
# ═══════════════════════════════════════════════════════════════════════

LIKELY_CASES = LIKELY_MID_SENTENCE + LIKELY_MIDWORD
UNLIKELY_CASES = _UNLIKELY_PAIRS


# ═══════════════════════════════════════════════════════════════════════
#  Parametrized tests
# ═══════════════════════════════════════════════════════════════════════


@pytest.mark.integration
@pytest.mark.continuation
@pytest.mark.parametrize(
    "first,second,min_score,test_id",
    LIKELY_CASES,
    ids=[c[3] for c in LIKELY_CASES],
)
def test_likely_continuation(first, second, min_score, test_id, api):
    """Text fragments that naturally continue from one another."""
    body = continuation_check(api, first, second)
    assert body["result"] == "likely_continuation", (
        f"[{test_id}] Expected likely_continuation: "
        f"'{first[:40]}...' -> '{second[:40]}...'"
    )
    assert body["score"] >= min_score, (
        f"[{test_id}] Score {body['score']} < min {min_score}"
    )


@pytest.mark.integration
@pytest.mark.continuation
@pytest.mark.parametrize(
    "first,second,max_score,test_id",
    UNLIKELY_CASES,
    ids=[c[3] for c in UNLIKELY_CASES],
)
def test_unlikely_continuation(first, second, max_score, test_id, api):
    """Text fragments that do NOT naturally continue from one another."""
    body = continuation_check(api, first, second)
    assert body["result"] == "unlikely_continuation", (
        f"[{test_id}] Expected unlikely_continuation: "
        f"'{first[:40]}...' -> '{second[:40]}...'"
    )
    assert body["score"] <= max_score, (
        f"[{test_id}] Score {body['score']} > max {max_score}"
    )
